### ISSUE TITLE
How to calculate a variable lenght on a bar?

### ISSUE THREAD

**Issue by RCSen** [gabemorris12/mechanism#3]
Hello.
I have a variable lengh on a bar due to a linear actuator, the triangle vector has 3 points (A B C), where A and C are blocked, B its the unknown position. How do you configure the script?, thank you so much and congratulations for the contribution.

**Comment by gabemorris12** [comment]
Hi,

It may be at the end of today or sometime tomorrow to when I can get around to it, but just to be clear, is this what you are describing?

![image](https://github.com/gabemorris12/mechanism/assets/73252281/33ab6e5c-d8fd-4dcd-8d26-c0f19b5786f6)

The distance between A and B is the only thing that moves? If this isn't it, then you providing a diagram would help. 

Thanks,
Gabe
